[build]
  base = "."
  command = "pnpm --filter @workspace/buildrmc build"
  publish = "artifacts/buildrmc/dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://rmc-edit.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
