[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd artifacts/api-server && pnpm build"]

[start]
cmd = "cd artifacts/api-server && node --enable-source-maps ./dist/index.mjs"
